name: swg
dependencies:
- python=3.5
- basemap=1.0.7
- matplotlib=1.4.3
- nltk=3.0.5
- numpy=1.9.2
- pandas=0.16.2
- seaborn=0.6.0
- pygments
- requests
- pip:
  - flickrapi==2.1.1
  - tweepy 
  - sphinx
  - sphinxcontrib-httpdomain
